using PipeWireAODeployment, TOML
const C=PipeWireAODeployment.Common
const S=PipeWireAODeployment.ScienceExport
const H=PipeWireAODeployment.HILExport
const D=PipeWireAODeployment.Deployment
source,output,runner,sdk=abspath.(ARGS)
isfile(runner) || error("runner executable required")
!ispath(output) || error("fresh output required")
before=C.read_json(joinpath(source,"deployment.conf"))
D.profile(joinpath(source,"deployment.conf"),"/opt/pipewireao")
for (path,hash) in before["artifacts"]
    C.sha256_file(joinpath(source,path))==hash || error("original seal changed: $path")
end
cp(source,output)
S.copy_deployment_runtime(output)
H.replace_staged_package(sdk,output,"PipeWireAO")
old_runner_sha=C.sha256_file(joinpath(output,"bin/pipewireao-rtc"))
cp(runner,joinpath(output,"bin/pipewireao-rtc");force=true)
chmod(joinpath(output,"bin/pipewireao-rtc"),0o755)
new_runner_sha=C.sha256_file(joinpath(output,"bin/pipewireao-rtc"))
manifest_path=joinpath(output,"julia/Manifest.toml")
manifest=TOML.parsefile(manifest_path)
dependency=only(manifest["deps"]["PipeWireAO"])
for key in ("git-tree-sha1","repo-url","repo-rev");pop!(dependency,key,nothing);end
dependency["path"]="../hil/packages/PipeWireAO"
open(io->TOML.print(io,manifest;sorted=true),manifest_path,"w")
# Installed unit files contain the installation path and are regenerated by
# Deployment.install. They are not scientific inputs or export artifacts.
isdir(joinpath(output,"systemd")) && rm(joinpath(output,"systemd");recursive=true)
protected=Dict(path=>hash for (path,hash) in before["artifacts"] if
    !startswith(path,"julia/") && !startswith(path,"systemd/") && path != "provenance.json" && path != "bin/pipewireao-rtc" && path != "hil/packages/PipeWireAO/src/thread_loop.jl")
for (path,hash) in protected
    C.sha256_file(joinpath(output,path))==hash || error("non-runtime byte changed: $path")
end
provenance=C.read_json(joinpath(output,"provenance.json"))
provenance["native_control_runtime_refresh"]=Dict("original"=>source,
    "descriptor_sha256"=>C.sha256_file(joinpath(source,"deployment.conf")),
    "protected_files"=>protected,"protected_count"=>length(protected),
    "source_revision"=>readchomp(`git -C $(dirname(dirname(dirname(dirname(pathof(PipeWireAODeployment)))))) rev-parse HEAD`),"helper_sha256"=>C.sha256_file(@__FILE__),
    "sdk_revision"=>readchomp(`git -C $sdk rev-parse HEAD`),
    "sdk_lock_source_sha256"=>C.sha256_file(joinpath(output,"hil/packages/PipeWireAO/src/thread_loop.jl")),
    "original_runner_sha256"=>old_runner_sha,"new_runner_sha256"=>new_runner_sha,
    "scope"=>"cold runtime and the reviewed SDK thread-loop source only; all other sealed bytes unchanged")
C.write_json(joinpath(output,"provenance.json"),provenance)
descriptor=copy(before);descriptor["name"]=basename(output)
descriptor["artifacts"]=H._package_artifacts(output)
C.write_json(joinpath(output,"deployment.conf"),descriptor)
D.profile(joinpath(output,"deployment.conf"),"/opt/pipewireao")
installed=output*"-installed"
D.install((;package=output,destination=installed,pipewire_prefix="/opt/pipewireao"))
sealed=C.read_json(joinpath(installed,"deployment.conf"))
for (path,hash) in sealed["artifacts"]
    C.sha256_file(joinpath(installed,path))==hash || error("installed seal changed: $path")
end
C.write_json(output*"-proof.json",Dict("installed"=>installed,
    "protected_count"=>length(protected),"protected_files"=>protected,
    "installed_seal_count"=>length(sealed["artifacts"]),
    "descriptor_sha256"=>C.sha256_file(joinpath(installed,"deployment.conf"))))
println(installed)
